baseURL: "https://informatiq.github.io"
languageCode: "en-us"
title: "Ramez Hanna"
theme: profile-ng

Paginate: 3
#disqusShortname: gurusabarish
googleAnalytics: G-N25TY2TYNR 

markup:
  goldmark:
    renderer:
      unsafe: true

enableEmoji: True

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: https://informatiq.medium.com/
      weight: 1

params:
  title: "Ramez Hanna"
  description: Coach and tech leader
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/favicon.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: True
    defaultTheme: "light" # dark
  
  # Site home
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ramez Hanna."
    subtitle: |-
      Leadership Coach 

    content: |-
      I work with aspiring leaders to help them achieve their goals and improve their performance.  
      Having spent 20+ years in tech working across different countries and cultures, I am well suited to work with engineering leaders around the world.  
      
      Whether you are an experienced leader looking to unlock your potential or taking your first leadership steps, coaching will help you get clarity and push in the right direction.
       
    image: "/images/hero-me.jpg"
    button:
      enable: true
      name: "Schedule a call"
      url: "https://calendly.com/ramez-hanna/45-minute-meeting"
      download: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ramezhanna/
  
  # Site sections
  sections:
    - Name: "You"
      enable: true
      title: "About You"
      image: "/images/you.png"
      content: |-
        #### Are you considering your next career step, and
        * Management is one of your options.
        * You are not sure where to go from here.

        **OR**

        #### You are in a leadership or management role, and
        * You are new at it and looking for help ramping up.
        * You are looking to grow into the role and enlarge your impact.
        * You received feedback that you want to work on.
        * You are questioning what your next step looks like.
        * You just want to get better at it.
        
        **OR** 

        #### Are you, as a person
        * Finding it hard to get through a certain sitaution?
        * Wanting to grow but unable to make a long-lasting impact.

        If you relate to any of the above, <a href="#" data-bs-toggle="modal" data-bs-target="#bookme">book a free call</a> with me to see how coaching can help you 

    - Name: "Coaching"
      enable: true
      title: "Coaching"
      image: "/images/butterfly-transform.png"
      content: |-
        #### What is coaching?
        Coaching is a form of development in which an experienced person, called a coach, supports a learner, called a coachee, in achieving a specific personal or professional goal by providing training and guidance.  
        In simple terms, coaching is an opportunity for the coachee to take the time to work on themselves with the help of a coach.  
        The coach helps the coachee in gaining clarity on their goals. Be mindful of their current ways. Paint a picture of the destination and support them in getting there.

        <img src="/images/coaching-diag.png" width="100%">

        #### How does it go?
        A coaching program has a start and an end.
        * It starts with the coachee having a topic to work on that is important to them and their development.
        * A discovery session, in which the coach and the coachee learn a little about each other, break the ice. They will also start to discover the topic. The purpose is for both to get clarity on the topic.
        * In the next session, the coach will propose a coaching program that is customized to the coachee that runs over several sessions (4-6 months). They will discuss and refine it together.
          The program will have clear goals and exercises to help the coachee achieve them.
        * Finally, there is a closing session to review and celebrate the change.  
        
        Yet the journey doesn’t stop there, the coach merely helps the coachee get on the path to achieving their goals.  
        After the program is over, the work goes on and the coachee continues on their journey of growth without the coach.  
        **Ready to step in? Let’s talk. <a href="#" data-bs-toggle="modal" data-bs-target="#bookme">Book a free call</a> with me.**

        #### Who is it for?
        Coaching can be helpful for individuals and teams who want to achieve their goals and improve their performance.
        It can be useful for people looking to make changes in their personal or professional lives, and who want support and guidance in achieving their goals.   
        Coaching can be useful for people looking to develop specific skills or knowledge, such as leadership or communication skills. It can also be helpful for people who are going through significant life transitions, such as a career change or a move to a new city.  
        
        Overall, coaching can be beneficial for anyone who wants to achieve personal and professional growth and fulfillment, and who is willing to put in the effort and commitment to make it happen.  
        **Not sure if that is for you? <a href="#" data-bs-toggle="modal" data-bs-target="#bookme">Book a free intro call</a> and we can walk through options.**

        #### What are the requirements?
        The only requirement is to have a topic.  
        A topic can be anything that you want to achieve or improve. It could even be about finding a goal.  
        **The best way to figure out if you are ready is to do it. <a href="#" data-bs-toggle="modal" data-bs-target="#bookme">Book a free call</a> with me and let's talk.**


    - Name: "Testimonials"
      enable: True
      title: "Testimonials"
      #image: "/images/testimonials.png"
      cards:
          - content: "I have truly had a transformative experience thanks to Ramez's coaching.  
          He skillfully identified the root cause of my struggle, despite my initial belief that it was a mere matter of procrastination and fatigue.  
          Now, [...] I feel less overwhelmed and better equipped to handle whatever comes my way.  
          I was skeptical at first, but now I am a true believer in the magic of coaching.  
          I highly recommend coaching by Ramez to anyone looking to make positive changes."
            footer: "Mother and Software developer"
          - content: "Mr. Ramez Hanna so far has been an exceptional and proficient coach. 
          His proficiency in startup processes and product development is unparalleled and has set him apart from other coaches and mentors I have had the privilege of working with in the past. 
          During our discussion sessions, he has consistently provided insightful guidance, leveraging his extensive knowledge and experience to yield positive results.
          I highly recommend Mr. Hanna for the profound impact he has made in both my personal and professional life. 
          His guidance and support have enabled me to overcome numerous challenges and achieve my goals, and I have no doubt that he will continue to inspire and impact those he coaches in the same way."
            footer: "Entrepreneur and SW engineer "
          - content: "Ramez has proved to be a dedicated coach.  
          I had the pleasure of knowing Ramez and working with him over 3 months.
          I was impressed with his ability to help me to identify my issues and how to make a transition from an engineer to a manager. 
          I have learned from him more than I could ever expect, so I strongly recommend Ramez as a professional that you are willing to work with."
            footer: "Robin Lui"
    - Name: "Aboutme"
      enable: true
      title: "About Me"
      image: "/images/ICC-IAC-style1.png"
      content: |-
        I had a career as an individual contributor in tech. Part of my job was to mentor less experienced engineers.  
        Later I moved into management, and started managing teams. This time mentoring was a big part of my job, both mentoring engineers and less experienced managers.  
        I always found mentoring useful, but for me, I didn't want advice, I was more looking to learn things myself, finding my way. That's when I learned about coaching.  
        
        I started integrating it into my tools as a manager. Quite a powerful tool too.  
        Coaching others helped me personally get better, and as I am who I am I did coaching in my own way after a lot of reading and experimenting with styles.  
        Later I had my own coaching experience as a coacheewhich was amazing experience. An eye-opener.  
        
        I have learned by doing, and went for coaching training. I have been able to help managers and engineers with their growth journeys and this has given me tremendous satisfaction. Coaching is quite rewarding and humbling.  
        Today I am here to be available for a bigger audience. <a href="#" data-bs-toggle="modal" data-bs-target="#bookme">Book a free call</a>, let's talk.
    - Name: "Contact"
      enable: true
      title: "Contact"
      content: |-
        For any questions or inquiries feel free to message me over [LinkedIn](https://www.linkedin.com/in/ramezhanna/) or email me at rhanna at informatiq dot org

  footer:
    recentPosts: false
    socialNetworks:
      #linkedin: https://linkedin.com/in/ramezhanna/
