baseURL: "https://informatiq.github.io"
languageCode: "en-us"
title: "Ramez Hanna"
theme: profile-ng

Paginate: 3
#disqusShortname: gurusabarish
googleAnalytics: G-N25TY2TYNR 

markup:
  goldmark:
    renderer:
      unsafe: true

enableEmoji: True

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: https://informatiq.medium.com/
      weight: 1

params:
  title: "Ramez Hanna"
  description: Coach and tech leader
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/favicon.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: True
    defaultTheme: "light" # dark
  
  # Site home
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ramez Hanna."
    subtitle: |-
      Leadership Coach 

    content: |-
      I work with aspiring leaders to help them achieve their goals and improve their performance.
      Having spent 20+ years in tech working across different countries and cultures, I am well suited to work with engineering leaders around the world.
      Whether you are taking the first steps or experienced and looking to unlock your potential.
       
    image: "/images/hero.jpg"
    button:
      enable: true
      name: "Schedule a call"
      url: "https://calendly.com/ramez-hanna"
      download: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ramezhanna/
  
  # Site sections
  sections:
    - Name: "You"
      enable: true
      title: "You"
      content: |-
        #### Are you considering your next career step, and
        * Management is one of your options?
        * Not sure where to go from here

        **OR**

        #### Are you in a leadership or management role, and
        * You are new at it and looking for help ramping up
        * Looking to grow into your role and enlarge your impact
        * You received feedback that you want to work on
        * Questioning what your next step looks like
        * You just want to get better at it
        
        **OR** 

        #### Are you, as a person
        * Finding it hard to get through a sitaution
        * Wanting to grow but unable to make long lasting impact

        If you relate to any of the above, [Schedule an intro call](https://calendly.com/ramez-hanna) with me to see how coaching can help you 

    - Name: "Coaching"
      enable: true
      title: "Coaching"
      #image: "/images/me-yellow.jpg"
      content: |-
        #### What is coaching?
        Coaching is a form of development in which an experienced person, called a coach, supports a learner, called coachee, in achieving a specific personal or professional goal by providing training and guidance.  
        In simple terms, coaching is an opportunity for the coachee to take the time to work on themselves with the help of a coach.  
        The coach helps the coachee in gaining clarity on their goals. Be mindful of their current ways. Paint a picture of the destination and support them in getting there.

        #### How does it go?
        A coaching program has a start and an end.
        * It starts with the coachee having a topic to work on that is important to them and their development.
        * A discovery session, in which the coach and the coachee learn a little about each other, break the ice. They will also start to discover the topic. The purpose is for both to get clarity on the topic.
        * In the next session, the coach will propose a coaching program that is customized to the coachee that runs over several sessions (4-6 months). They will discuss and refine it together.
          The program will have clear goals and exercises to help the coachee achieve them.
        * Finally, a closing session to review and celebrate the change.  
        
        Yet the journey doesn’t stop there, the coach merely helps the coachee get on the path to achieving their goals.  
        After the program is over, the work continues and the coachee continues on their journey of growth without the coach.  
        **Ready to step in? Let’s talk. [Schedule an intro call](https://calendly.com/ramez-hanna) with me.**

        #### Who is it for?
        Coaching can be helpful for individuals and teams who want to achieve their goals and improve their performance. It can be useful for people who are looking to make changes in their personal or professional lives, and who want support and guidance in achieving their goals.  
        Coaching can be useful for people who are looking to develop specific skills or knowledge, such as leadership or communication skills. It can also be helpful for people who are going through significant life transitions, such as a career change or a move to a new city.  
        Overall, coaching can be beneficial for anyone who wants to achieve personal and professional growth and fulfillment, and who is willing to put in the effort and commitment to make it happen.  
        **Not sure if that is for you? [Book a free demo session](https://calendly.com/ramez-hanna)**

        #### What are the requirements?
        The only requirement is to have  a topic.  
        A topic can be anything that you want to acheive or improve. It could even be about finidng a goal.  
        **The best way to figure out if you are ready is to do it. [Book a free introductory session](https://calendly.com/ramez-hanna) and let's talk.**


    - Name: "Testimonials"
      enable: false
      title: "Testimonials"
      #image: "/images/testimonials.png"
      cards:
          - content: "he the most amazing amaze"
            footer: "anonymous"
          - content: "so much wow, so much amaze"
            footer: "anonymous"
          - content: "he the most amazing amaze"
            footer: "anonymous"
    - Name: "Aboutme"
      enable: true
      title: "About Me"
      #image: "/images/me-yello.jpg"
      content: |-
        I had a career as an individual contributor in tech. Part of my job was to mentor less experienced engineers.  
        Later I moved into management, and started managing teams. This time mentoring was a big part of my job, both mentoring engineers and less experienced managers.  
        I always found mentoring useful, but for me, I didn't want advice, I was more looking to learn things myslef, finding my way. That's when I learned about coaching.  
        I started integrating it in my tools as a manager. Quite a powerful tool too.  
        Coaching others helped me personally get better, and as I am who I am I did coaching in my own way after a lot of reading and experimenting with styles.  
        Later I had my own coaching experience as a coachee, and it was an amazing experience. An eye opener.  
        
        I have learned by doing, and went for coaching training. I have been able to help managers and engineers with their growth journeys.  
        This has given me tremendous satisfaction. Coaching is quite rewarding and humbling.  
        Today I am here to be available for a bigger audience. [Schedule a call](https://calendly.com/ramez-hanna)
    - Name: "Contact"
      enable: true
      title: "Contact"
      content: |-
        For any questions or inquiries feel free to message me over linkedin or email me at rhanna at informatiq dot org

  footer:
    # recentPosts: false
    socialNetworks:
      linkedin: https://linkedin.com/in/ramezhanna/
